MASTER_PARAMETERS = [
    "Hemoglobin (Hb)",
    "Total Leucocytes (WBC) count",
    "Platelet count",
    "Red blood cell (RBC) count",
    "PCV (Packed Cell Volume)",
    "MCV (Mean Corpuscular Volume)",
    "MCH (Mean Corpuscular Hb)",
    "MCHC (Mean Corpuscular Hb Conc.)",
    "RDW (RBC distribution width)",
    "MPV (Mean Platelet Volume)",
    "Neutrophils",
    "Absolute Neutrophils",
    "Eosinophils",
    "Absolute Eosinophils",
    "Basophils",
    "Absolute Basophils",
    "Lymphocytes",
    "Absolute Lymphocytes",
    "Monocytes",
    "Absolute Monocytes",
    "Cholesterol (Total)",
    "Triglycerides",
    "HDL Cholesterol",
    "VLDL Cholesterol",
    "LDL Cholesterol",
    "Cholesterol/HDL Ratio",
    "LDL/HDL Ratio",
    "Apolipoprotein A1",
    "Apolipoprotein B",
    "ApoB/A1 Ratio",
    "Bilirubin-Total",
    "Bilirubin-Conjugated",
    "Bilirubin-Unconjugated",
    "SGOT (AST)",
    "SGPT (ALT)",
    "Alkaline Phosphatase",
    "Protein (Total)",
    "Albumin",
    "Globulin",
    "Plasma Glucose Fasting",
    "Urea",
    "BUN (Blood Urea Nitrogen)",
    "Creatinine",
    "Vitamin D",
    "Vitamin B12",
    "Insulin Fasting",
    "Free T3",
    "Free T4",
    "TSH (Ultrasensitive)",
    "HbA1C",
    "Estimated Average Glucose (eAG)",
    "PSA",
    "CRP(hs)",
    "Calcium",
    "ESR (Erythrocyte Sedimentation Rate)",
    "Urine Routine Examination pH",
    "Urine Routine Examination Protein",
    "Urine Routine Examination Glucose",
    "Urine Routine Examination Acetone",
    "Urine Routine Examination Bile Pigments",
    "Urine Routine Examination Urobilinogen",
    "Urine Routine Examination RBCs",
    "Urine Routine Examination Pus cells",
    "Urine Routine Examination Epithelial cells",
    "Urine Routine Examination Casts",
    "Urine Routine Examination Crystals",
    "Urine Routine Examination Quantity Examined",
    "Urine Routine Examination Appearance",
    "Urine Routine Examination Colour"
]

SECTION_MAPPING = {
        "Hemoglobin (Hb)": "Complete Blood Count",
        "Total Leucocytes (WBC) count": "Complete Blood Count",
        "Platelet count": "Complete Blood Count",
        "Red blood cell (RBC) count": "Complete Blood Count",
        "PCV (Packed Cell Volume)": "Complete Blood Count",
        "MCV (Mean Corpuscular Volume)": "Complete Blood Count",
        "MCH (Mean Corpuscular Hb)": "Complete Blood Count",
        "MCHC (Mean Corpuscular Hb Conc.)": "Complete Blood Count",
        "RDW (RBC distribution width)": "Complete Blood Count",
        "MPV (Mean Platelet Volume)": "Complete Blood Count",
        "Neutrophils": "Complete Blood Count",
        "Absolute Neutrophils": "Complete Blood Count",
        "Eosinophils": "Complete Blood Count",
        "Absolute Eosinophils": "Complete Blood Count",
        "Basophils": "Complete Blood Count",
        "Absolute Basophils": "Complete Blood Count",
        "Lymphocytes": "Complete Blood Count",
        "Absolute Lymphocytes": "Complete Blood Count",
        "Monocytes": "Complete Blood Count",
        "Absolute Monocytes": "Complete Blood Count",

        # Lipid Profile Maxi
        "Cholesterol (Total)": "Lipid Profile Maxi",
        "Triglycerides": "Lipid Profile Maxi",
        "HDL Cholesterol": "Lipid Profile Maxi",
        "VLDL Cholesterol": "Lipid Profile Maxi",
        "LDL Cholesterol": "Lipid Profile Maxi",
        "Cholesterol/HDL Ratio": "Lipid Profile Maxi",
        "LDL/HDL Ratio": "Lipid Profile Maxi",
        "Apolipoprotein A1": "Lipid Profile Maxi",
        "Apolipoprotein B": "Lipid Profile Maxi",
        "ApoB/A1 Ratio": "Lipid Profile Maxi",

        # Liver Function Test
        "Bilirubin-Total": "Liver Function Test",
        "Bilirubin-Conjugated": "Liver Function Test",
        "Bilirubin-Unconjugated": "Liver Function Test",
        "SGOT (AST)": "Liver Function Test",
        "SGPT (ALT)": "Liver Function Test",
        "Alkaline Phosphatase": "Liver Function Test",
        "Protein (Total)": "Liver Function Test",
        "Albumin": "Liver Function Test",
        "Globulin": "Liver Function Test",
        "HbA1C": "Liver Function Test",
        "Estimated Average Glucose (eAG)": "Liver Function Test",

        # Plasma Glucose
        "Plasma Glucose Fasting": "Plasma Glucose",

        # Clinical Chemistry
        "Urea": "Clinical Chemistry",
        "BUN (Blood Urea Nitrogen)": "Clinical Chemistry",
        "Creatinine": "Clinical Chemistry",



        # Hormones
        "Insulin Fasting": "Hormones",
        "Free T3": "Hormones",
        "Free T4": "Hormones",
        "TSH (Ultrasensitive)": "Hormones",
        "PSA": "Hormones",
        "Vitamin D": "Hormones",
        "Vitamin B12": "Hormones",

        # Haematology
        "ESR (Erythrocyte Sedimentation Rate)": "Haematology",

        # Urine Routine Examination
        "pH": "Urine Routine Examination",
        "Protein": "Urine Routine Examination",
        "Glucose": "Urine Routine Examination",
        "Acetone": "Urine Routine Examination",
        "Bile Pigments": "Urine Routine Examination",
        "Urobilinogen": "Urine Routine Examination",
        "RBCs": "Urine Routine Examination",
        "Pus cells": "Urine Routine Examination",
        "Epithelial cells": "Urine Routine Examination",
        "Casts": "Urine Routine Examination",
        "Crystals": "Urine Routine Examination",
        "Quantity Examined": "Urine Routine Examination",
        "Appearance": "Urine Routine Examination",
        "Colour": "Urine Routine Examination"

    }