from pyspark.sql.types import StructType, StructField, StringType, DoubleType, DateType


health_report_schema= StructType([
    StructField("context",StructType([
        StructField("patient", StringType(), True),
        StructField("date", DateType(),True)
    ])),
    StructField("Data",StructType([
        StructField("Hemoglobin (Hb)", DoubleType(), True),
        StructField("Total Leucocytes (WBC) count", DoubleType(), True),
        StructField("Platelet count", DoubleType(), True),
        StructField("Red blood cell (RBC) count", DoubleType(), True),
        StructField("PCV (Packed Cell Volume)", DoubleType(), True),
        StructField("MCV (Mean Corpuscular Volume)", DoubleType(), True),
        StructField("MCH (Mean Corpuscular Hb)", DoubleType(), True),
        StructField("MCHC (Mean Corpuscular Hb Conc.)", DoubleType(), True),
        StructField("RDW (RBC distribution width)", DoubleType(), True),
        StructField("Neutrophils", DoubleType(), True),
        StructField("Absolute Neutrophils", DoubleType(), True),
        StructField("Eosinophils", DoubleType(), True),
        StructField("Absolute Eosinophils", DoubleType(), True),
        StructField("Basophils", DoubleType(), True),
        StructField("Absolute Basophils", DoubleType(), True),
        StructField("Lymphocytes", DoubleType(), True),
        StructField("Absolute Lymphocytes", DoubleType(), True),
        StructField("Monocytes", DoubleType(), True),
        StructField("Absolute Monocytes", DoubleType(), True),
        StructField("Cholesterol (Total), serum by Enzymatic method", DoubleType(), True),
        StructField("Triglycerides, serum by Enzymatic method", DoubleType(), True),
        StructField("HDL Cholesterol, serum by Enzymatic method", DoubleType(), True),
        StructField("VLDL Cholestrol, serum by calculation", DoubleType(), True),
        StructField("LDL Cholesterol, serum by calculation", DoubleType(), True),
        StructField("Triglycerides", DoubleType(), True),
        StructField("LDL Cholesterol, serum", DoubleType(), True),
        StructField("Cholesterol(Total)/HDL Cholesterol Ratio", DoubleType(), True),
        StructField("LDL Cholesterol/HDL Cholesterol Ratio", DoubleType(), True),
        StructField("Apolipoprotein A1, serum", DoubleType(), True),
        StructField("Apolipoprotein B, serum", DoubleType(), True),
        StructField("Apolipoprotein A1, serum by Nephelometry", DoubleType(), True),
        StructField("Apolipoprotein B, serum by Nephelometry", DoubleType(), True),
        StructField("Bilirubin-Total, serum", DoubleType(), True),
        StructField("Bilirubin-Conjugated, serum", DoubleType(), True),
        StructField("Bilirubin-Unconjugated, serum", DoubleType(), True),
        StructField("SGOT (AST), serum", DoubleType(), True),
        StructField("SGPT (ALT), serum", DoubleType(), True),
        StructField("Alkaline Phosphatase, serum", DoubleType(), True),
        StructField("Protein (total), serum", DoubleType(), True),
        StructField("Albumin, serum", DoubleType(), True),
        StructField("Globulin, serum", DoubleType(), True),
        StructField("Glycated Hemoglobin (HbA1C)", DoubleType(), True),
        StructField("Adults", DoubleType(), True),
        StructField("Toddlers and Preschoolers", DoubleType(), True),
        StructField("School age (6-12 yrs)", DoubleType(), True),
        StructField("Adolescents and young adults (13 - 19 yrs)", DoubleType(), True),
        StructField("Gamma Glutamyl Transferase (GGT)", DoubleType(), True),
        StructField("Plasma glucose fasting, by Hexokinase method", DoubleType(), True),
        StructField("Plasma Glucose Fasting", DoubleType(), True),
        StructField("Urea, Serum", DoubleType(), True),
        StructField("Blood Urea Nitrogen, Serum", DoubleType(), True),
        StructField("Creatinine, Serum", DoubleType(), True),
        StructField("Uric Acid, Serum", DoubleType(), True),
        StructField("Calcium, serum by OCPC method", DoubleType(), True),
        StructField("Calcium, serum", DoubleType(), True),
        StructField("Hypercalcemia", DoubleType(), True),
        StructField("Calcium", DoubleType(), True),
        StructField("Hypocalcemia", DoubleType(), True),
        StructField("Free T3, serum by CMIA", DoubleType(), True),
        StructField("Free T4, serum by CMIA", DoubleType(), True),
        StructField("TSH(Ultrasensitive), serum by CMIA", DoubleType(), True),
        StructField("Free T3", DoubleType(), True),
        StructField("Free T4", DoubleType(), True),
        StructField("TSH(Ultrasensitive)", DoubleType(), True),
        StructField("Insulin Fasting", DoubleType(), True),
        StructField("Vitamin B12, serum by CMIA", DoubleType(), True),
        StructField("Vitamin B12", DoubleType(), True),
        StructField("Serum methylmalonic acid", DoubleType(), True),
        StructField("Homocysteine", DoubleType(), True),
        StructField("Active B12 (Holotranscobalamin)", DoubleType(), True),
        StructField("25 - OH Vitamin D, serum by CMIA", DoubleType(), True),
        StructField("Quantity Examined", DoubleType(), True),
        StructField("pH", DoubleType(), True),
        StructField("Acetone", DoubleType(), True),
        StructField("Bile Pigments", DoubleType(), True),
        StructField("Urobilinogen", DoubleType(), True),
        StructField("R.B.Cs", DoubleType(), True),
        StructField("Pus cells", DoubleType(), True),
        StructField("Epithelial cells", DoubleType(), True),
        StructField("Casts", DoubleType(), True),
        StructField("Crystals", DoubleType(), True)
    ]))
])
